GET http://localhost:5000/

### Login Route
POST http://localhost:5000/auth/login

### register Route
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "atsajeev56778nw@gmail.com",
    "password": "123456"
}

### Refresh token Route
POST http://localhost:5000/auth/refresh-token

### logout Route
DELETE http://localhost:5000/auth/logout
